apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend-service.name }}
spec:
  type: {{ .Values.backend-service.type }}
  ports:
    - port:  {{ .Values.backend-deployment.containers.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ .Values.backend-deployment.containers.name }}