apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendService.name }}
spec:
  type: {{ .Values.backendService.type }}
  ports:
    - port:  {{ .Values.backendDeployment.containers.Port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ .Values.backendDeployment.containers.name }}