apiVersion: apps/v1
kind: authDeployment
metadata:
  name: {{ .Values.authDeployment.name }}
spec:
  replicas: {{ .Values.authDeployment.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.authDeployment.containers.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.authDeployment.containers.name }}
    spec:
      containers:
      - name: {{ .Values.authDeployment.containers.name }}
        image: ahmedsamy98/app-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.authDeployment.containers.port }}
        env:
          - name: DB_HOST
            value: mysql
          - name: DB_USER
            value: authuser
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: auth-password
          - name: DB_NAME
            value: weatherapp
          - name: DB_PORT
            value: "3306"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: secret-key