
mysqlStatefulset:
  name: mysqlStatefulset
  replicas: 1
  labels:
    app: mysql
  containers:
    name: mysql-container
    image: mysql:latest 
    port: 3306
  pvc:
    name: mysql-persistent-storage
    storage: 10G

mysqlStorageClass:
  name: ebs-gp2

mysqlService:
  name: mysql
  labels:
    app: mysql
  port: 3306

mysqlStatefulset:
  name: mysqlStatefulset
  replicas: 1
  labels:
    app: mysql
  containers:
    name: mysql-container
    image: mysql:latest 
    port: 3306
  pvc:
    name: mysql-persistent-storage
    storage: 10G

mysqlInitJob:
  name: mysql-init-job