apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: weatherapp-backend
  template:
    metadata:
      labels:
        name: weatherapp-backend
    spec:
      containers:
        - name: weatherapp-backend
          image: ahmedsamy98/app-weather:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: weather-secret
                key: apikey
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          