apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      name: weatherapp-ui
  template:
    metadata:
      labels:
        name: weatherapp-ui
    spec:
      containers:
        - name: weatherapp-ui
          image: ahmedsamy98/app-ui
          imagePullPolicy: IfNotPresent
          env:
          - name: AUTH_HOST
            value: weatherapp-auth
          - name: AUTH_PORT
            value: "8080"
          - name: WEATHER_HOST
            value: weatherapp-backend
          - name: WEATHER_PORT
            value: "5000"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http