apiVersion: v1
kind: Service
metadata:
  name: weatherapp-ui
spec:
  type: {{ .Values.uiweatherService.type }}
  ports:
    - port:  {{ .Values.uiweather.containers.Port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ .Values.uiweather.containers.name }}