apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqlStatefulset
spec:
  serviceName: {{ .Values.mysqlService.name }}
  replicas: {{ .Values.mysqlStatefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysqlStatefulset.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysqlStatefulset.labels.app }}
    spec:
      containers:
      - name: {{ .Values.mysqlStatefulset.containers.app }}
        image: mysql:latest 
        ports:
        - containerPort: {{ .Values.mysqlStatefulset.containers.port }}
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.mysqlStatefulset.pvc.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.mysqlStorageClass.name }}
      resources:
        requests:
          storage: {{ .Values.mysqlStatefulset.pvc.storage }}