apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .values.mysql-storage-class.name}}
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer