name: CI pipline
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build Auth image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-auth:latest ./App/auth

    - name: Push Auth image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-auth:latest

    - name: Build UI image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-ui:latest ./App/UI

    - name: Push UI image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-ui:latest

    - name: Build weather image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-weather:latest ./App/weather

    - name: Push weather image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-weather:latest
